#!/bin/bash

#cargo build
echo "Starting new build."\
 &&\
 CARGO_INCREMENTAL=0\
 RUST_TARGET_PATH="$PWD"\
 xargo build -p server --bin nxusb --target=aarch64-none-elf --release --features="libnx" --verbose\
 &&\
 echo "Compiled rust target. Now creating nro."\
 &&\
 elf2nro target/aarch64-none-elf/release/nxusb.nx_elf nxusb.nro\
 &&\
 echo "Finished making nro."