#!/bin/bash

#cargo build
echo "Starting new build."\
 &&\
 CARGO_INCREMENTAL=0\
 RUST_TARGET_PATH="$PWD"\
 RUST_BACKTRACE=1\
 xargo build --bin nxusb --target=aarch64-none-elf --verbose\
 &&\
 echo "Compiled rust target. Now creating nro."\
 &&\
 elf2nro target/aarch64-none-elf/release/nxusb.nx_elf nxusb.nro\
 &&\
 echo "Finished making nro."