#!/bin/bash

#cargo build
echo "Starting new build."\
 &&\
 CARGO_INCREMENTAL=0\
 RUST_TARGET_PATH="$PWD"\
 xargo build -p server --bin server --target=aarch64-none-elf --release --verbose\
 &&\
 echo "Compiled rust target. Now creating nro."\
 &&\
 elf2nro target/aarch64-none-elf/release/server.nx_elf nxusb_server.nro\
 &&\
 echo "Finished making nro."